# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

parameters:
- name: dockerComposeCommand
  displayName: docker-compose command
  type: string
  default: up
  values:
  - 'up -d'
  - down --rmi all

trigger:
- docker-compose-branch

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: 
     name: 'dotnet-agent-pool'
    steps:
    
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Write your PowerShell commands here.
          dotnet dev-certs https -ep ./https/weatherapi.pfx -p $(password_cert)
    - task: DockerCompose@0
      inputs:
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up -d'
