version: '3.7'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sql_server_container
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SQL_PASS}
      MSSQL_PID: Express

  webapi_development:
    restart: always
    container_name: webapi_container_development${TAG}
    image: webapi_image_development:${TAG}
    build:
      context: .
      dockerfile: Dockerfile-backend
      args:
        PASSWORD_CERT: ${PASSWORD_CERT}
        ENVIRONMENT: ${ENVIRONMENT}
        SQL_PASS: ${SQL_PASS}
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    links:
      - ms-sql-server

    webui_development:
      restart: always
      container_name: webui_container_development${TAG}
      image: webui_image_development:${TAG}
      build:
        context: .
        dockerfile: Dockerfile-backend

      ports:
        - "80:80"
      links:
        - webapi_development