FROM node:12.22.7-alpine as builder
WORKDIR /app
ARG ENVIRONMENT="Development"
RUN export CUSTOM_ENVIRONMENT=$(echo "$ENVIRONMENT" | tr '[:upper:]' '[:lower:]')
COPY ./weather-ui/package*.json .
RUN npm install
COPY ./weather-ui/ .
RUN npm run build-$CUSTOM_ENVIRONMENT

FROM nginx:1.20
WORKDIR /app
COPY ./weather-ui/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /app/dist/weather-ui /usr/share/nginx/html 
